[package]
name = 'merkle-distributor'
version = '1.0.0'
[addresses]
mokshya = "_"
[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'aptos-framework-v1.2.0',subdir = 'aptos-move/framework/aptos-framework' }
